# NumPy Arrays

In [12]:
#import numpy library
import numpy as np


In [2]:
#define your own list



In [3]:
#convert your list into the numpy array



In [4]:
#define your own matrix



In [5]:
#convert your matrix into the numpy array 


In [6]:
#Return evenly spaced values within a given interval (use:arrange)



In [7]:
#Return evenly spaced numbers over a specified interval (use:linspace)


In [8]:
#Creates an array of the given shape and populates 
#it with random samples from a uniform distribution over [0, 1) (use:rand)



In [9]:
#Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. 
#Unlike rand which is uniform, values closer to zero are more likely to appear (use:randn)



In [10]:
#Returns random integers from low (inclusive) to high (exclusive) (use: randint)



In [13]:
#use these two lines of code
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
arr
#ranarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
#change the shape of arr


In [21]:
#find min, max,index location of min and max (argmin, argmax)


In [22]:
#find the data type of the arr


# NumPy Indexing and Selection

In [23]:
#Creating sample array
arr = np.arange(0,11)
#show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
#Get a value at an index 8


In [25]:
#Get values in a range (1-5)


In [26]:
#Setting a value with index range 0-5 as 100 (Broadcasting)


In [27]:
#Indexing a 2D array (matrices)
#The general format is arr_2d[row][col] or arr_2d[row,col]. 
#I recommend using the comma notation for clarity.

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
#find the values for first row


In [29]:
#find the individual element value in row 1 and col0


In [30]:
# 2D array slicing

#Shape (2,2) from top right corner


In [35]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

# NumPy Operations

In [33]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
#use diffrent operations for arr array (+,-,/) and show your results


In [35]:
#Taking Square Roots of array


In [36]:
#Calculating exponential (e^)



Axis Logic:

When working with 2-dimensional arrays (matrices) we have to consider rows and columns. This becomes very important when we get to the section on pandas. In array terms, axis 0 (zero) is the vertical axis (rows), and axis 1 is the horizonal axis (columns).

These values (0,1) correspond to the order in which arr.shape values are returned.


In [37]:
#use this numpy array
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
#get sum of axis 0


# NumPy_Review_Exercises

In [40]:
#1. Import NumPy as np


In [41]:
#2. Create an array of 10 zeros (use zeros() function)


In [42]:
#3. Create an array of 10 ones (use ones() function)


In [43]:
#4. Create an array of 10 fives


In [44]:
#5. Create an array of the integers from 10 to 50


In [45]:
#6. Create an array of all the even integers from 10 to 50



In [46]:
#7. Create a 3x3 matrix with values ranging from 0 to 8


In [47]:
#8. Create a 3x3 identity matrix (.eye() function)


In [48]:
#9. Use NumPy to generate a random number between 0 and 1


In [49]:
#10. Use NumPy to generate an array of 25 random numbers sampled from a standard 
#normal distribution


In [50]:
#12. Create an array of 20 linearly spaced points between 0 and 1


In [51]:
#Now you will be given a starting matrix (be sure to run the cell below!), 
#and be asked to replicate the resulting matrix outputs

# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [59]:
#13. Write code that reproduces the output shown below.


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [52]:
#14. Write code that reproduces the output 20.


In [61]:
#15. Write code that reproduces the output shown below.


array([[ 2],
       [ 7],
       [12]])

In [62]:
#16. Write code that reproduces the output shown below.


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [53]:
#18. Get the sum of all the values in mat


In [54]:
#19. Get the standard deviation of the values in mat


In [55]:
#20. Get the sum of all the columns in mat
