# NumPy Arrays

In [2]:
#import numpy library
import numpy as np

In [15]:
#define your own list
# L = [1,2,3]
L = list(range(5))
L

[0, 1, 2, 3, 4]

In [17]:
#convert your list into the numpy array
A = np.array(L)
A

array([0, 1, 2, 3, 4])

In [35]:
#define your own matrix
M = [[1,4,6],
     [8,0,12]]
M

[[1, 4, 6], [8, 0, 12]]

In [38]:
#convert your matrix into the numpy array 
AM = np.array(M)
AM

array([[ 1,  4,  6],
       [ 8,  0, 12]])

In [42]:
#Return evenly spaced values within a given interval (use:arrange)
np.arange(4,20,3)

array([ 4,  7, 10, 13, 16, 19])

In [47]:
#Return evenly spaced numbers over a specified interval (use:linspace)
np.linspace(15,30,13)

array([15.  , 16.25, 17.5 , 18.75, 20.  , 21.25, 22.5 , 23.75, 25.  ,
       26.25, 27.5 , 28.75, 30.  ])

In [50]:
#Creates an array of the given shape and populates 
#it with random samples from a uniform distribution over [0, 1) (use:rand)
np.random.rand(5) 

array([0.58115125, 0.95156283, 0.68644158, 0.1912728 , 0.18430593])

In [53]:
#Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. 
#Unlike rand which is uniform, values closer to zero are more likely to appear (use:randn)
np.random.randn(5,5) 

array([[ 1.20298178, -1.69671074,  0.08083714,  1.11808961,  0.76257961],
       [ 0.08818725, -0.63704758, -1.01896225, -1.67905623,  0.44246888],
       [ 1.01554057,  0.0324568 ,  0.86056984, -0.27049343, -0.87256364],
       [-0.14510059,  0.36095437,  0.39255081, -0.35834485,  1.56488284],
       [ 0.16072328,  1.30428846, -0.25209752, -1.40004926,  1.09308237]])

In [56]:
#Returns random integers from low (inclusive) to high (exclusive) (use: randint)
np.random.randint(1,8,5) 

array([2, 1, 7, 1, 1])

In [57]:
#use these two lines of code
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
arr
ranarr

array([46,  5,  2, 12, 12, 37, 39, 17, 42,  2])

In [77]:
#change the shape of arr
#np.reshape(arr, newshape=(25,1))
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [82]:
#find min, max,index location of min and max (argmin, argmax)
arr.min()
arr.max()
arr.argmin()
arr.argmax() 

24

In [83]:
#find the data type of the arr
arr.dtype

dtype('int64')

# NumPy Indexing and Selection

In [84]:
#Creating sample array
arr = np.arange(0,11)
#show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
#Get a value at an index 8
arr[8] 

8

In [94]:
#Get values in a range (1-5)
arr[1:5] 

array([1, 2, 3, 4])

In [96]:
#Setting a value with index range 0-5 as 100 (Broadcasting)
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [134]:
#Indexing a 2D array (matrices)
#The general format is arr_2d[row][col] or arr_2d[row,col]. 
#I recommend using the comma notation for clarity.
arr_2d = np.array( ([5,10,15],[20,25,30],[35,40,45]) ) 
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [103]:
#find the values for first row
arr_2d[0] 

array([ 5, 10, 15])

In [104]:
#find the individual element value in row 1 and col0
arr_2d[1][0]

20

In [110]:
# 2D array slicing
#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [113]:
#Shape bottom row
#arr_2d[2]
arr_2d[2,:]

array([35, 40, 45])

# NumPy Operations

In [115]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
#use diffrent operations for arr array (+,-,/) and show your results
print(arr/2)
print(arr*3)
print(arr-1)
print(arr+4)
print(arr+arr)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 0  3  6  9 12 15 18 21 24 27]
[-1  0  1  2  3  4  5  6  7  8]
[ 4  5  6  7  8  9 10 11 12 13]
[ 0  2  4  6  8 10 12 14 16 18]


In [130]:
#Taking Square Roots of array
print(arr**(0.5))
print(np.sqrt(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [133]:
#Calculating exponential (e^)
print(np.exp(arr))

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


Axis Logic:

When working with 2-dimensional arrays (matrices) we have to consider rows and columns. This becomes very important when we get to the section on pandas. In array terms, axis 0 (zero) is the vertical axis (rows), and axis 1 is the horizonal axis (columns).

These values (0,1) correspond to the order in which arr.shape values are returned.


In [137]:
#use this numpy array
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [143]:
#get sum of axis 0
#np.sum(arr_2d,axis=1)
#arr_2d.sum(axis=1)
for i in range(len(arr_2d)):
    print(" sum of row ", i, ":", arr_2d[i].sum() )

 sum of row  0 : 10
 sum of row  1 : 26
 sum of row  2 : 42


# NumPy_Review_Exercises

In [149]:
#1. Import NumPy as np
import numpy as np

In [188]:
#2. Create an array of 10 zeros (use zeros() function)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [187]:
#3. Create an array of 10 ones (use ones() function)
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [186]:
#4. Create an array of 10 fives
#np.ones(10)
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [185]:
#5. Create an array of the integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [191]:
#6. Create an array of all the even integers from 10 to 50
np.arange(10,51,2) 

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [193]:
#7. Create a 3x3 matrix with values ranging from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [195]:
#8. Create a 3x3 identity matrix (.eye() function)
np.eye(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [198]:
#9. Use NumPy to generate a random number between 0 and 1
np.random.rand()

0.43571248120894635

In [200]:
#10. Use NumPy to generate an array of 25 random numbers sampled from a standard 
#normal distribution
np.random.randn(25) 

array([-1.39784903,  0.39908487, -1.69178377,  0.99550958,  1.44328907,
       -0.62681436, -2.14825704, -0.49116291,  0.12289895, -0.6385483 ,
       -0.78017923, -0.11838849,  0.44536607, -1.29696356, -0.32711041,
        0.70897461,  0.68029059, -0.36785276,  0.59563814,  2.54377057,
       -0.49341676, -2.55999679, -0.82587468,  0.41870176, -0.83256003])

In [203]:
#11. Create an array of 20 linearly spaced points between 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [204]:
#12. Now you will be given a starting matrix (be sure to run the cell below!), 
#    and be asked to replicate the resulting matrix outputs

# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [235]:
mat.mean()

13.0

In [209]:
#13. Write code that reproduces the output shown below.
mat[2:,1:] 

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [210]:
#14. Write code that reproduces the output 20.
mat[3,4] 

20

In [225]:
#15. Write code that reproduces the output shown below.
mat[:3,1:2]  

array([[ 2],
       [ 7],
       [12]])

In [227]:
#16. Write code that reproduces the output shown below.
mat[3:] 

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [228]:
#17. Get the sum of all the values in mat
mat.sum() 

325

In [232]:
#19. Get the standard deviation of the values in mat
mat.std() 

7.211102550927978

In [233]:
#20. Get the sum of all the columns in mat
mat.sum(axis=0) 

array([55, 60, 65, 70, 75])